/* eslint-disable */
// @ts-nocheck
/**
 * Some of the scripts creating generated scripts are
 * dependant on 3rd party libraries.
 * These 3rd party libraries sometimes generate code
 * that would cause errors, like creating unused variables.
 * While said errors would not cause compilation problems,
 * it does disrupt strict error checks.
 * For this unfortunate reason, eslint-disable and ts-nocheck
 * are at the top of the file, to tell eslint and
 * the TypeScript compiler not to run any error checks.
 *
 * This file was dynamically generated via script.
 * Generated files should NOT be edited by hand.
 * If you need to change something,
 * edit the script that created this file
 * or the file that it generated this script from.
 * The generation scripts are located inside of
 * {project}/config/generate/*.
 *
 * Any UTF-8 file that starts exactly with
 * directive eslint-disable, directive ts-nocheck,
 * and this comment block, character by character,
 * will be considered a generated file.
 * Files with these exact comments will be deleted if you use:
 * npm run clean:generated
 */
//This file was generated by script:
//config/generate/json-schema/validators/GenerateValidators.ts

"use strict";
export const validatePoint3 = validate10;
const schema11 = {
    $schema: "http://json-schema.org/draft-07/schema",
    $id: "urn:module:math/geometry/Point3.schema.json",
    title: "Point3",
    description: "Represents a 3d coordinate in space.",
    type: "object",
    properties: {
        x: {
            description: "X coordinate of the position.",
            type: "number",
            default: 0,
        },
        y: {
            description: "Y coordinate of the position.",
            type: "number",
            default: 0,
        },
        z: {
            description: "Z coordinate of the position.",
            type: "number",
            default: 0,
        },
    },
    required: ["x", "y", "z"],
    additionalProperties: true,
};

function validate10(
    data,
    { instancePath = "", parentData, parentDataProperty, rootData = data } = {},
) {
    /*# sourceURL="urn:module:math/geometry/Point3.schema.json" */ let vErrors =
        null;
    let errors = 0;
    if (data && typeof data == "object" && !Array.isArray(data)) {
        if (data.x === undefined) {
            const err0 = {
                instancePath,
                schemaPath: "#/required",
                keyword: "required",
                params: { missingProperty: "x" },
            };
            if (vErrors === null) {
                vErrors = [err0];
            } else {
                vErrors.push(err0);
            }
            errors++;
        }
        if (data.y === undefined) {
            const err1 = {
                instancePath,
                schemaPath: "#/required",
                keyword: "required",
                params: { missingProperty: "y" },
            };
            if (vErrors === null) {
                vErrors = [err1];
            } else {
                vErrors.push(err1);
            }
            errors++;
        }
        if (data.z === undefined) {
            const err2 = {
                instancePath,
                schemaPath: "#/required",
                keyword: "required",
                params: { missingProperty: "z" },
            };
            if (vErrors === null) {
                vErrors = [err2];
            } else {
                vErrors.push(err2);
            }
            errors++;
        }
        if (data.x !== undefined) {
            let data0 = data.x;
            if (!(typeof data0 == "number" && isFinite(data0))) {
                const err3 = {
                    instancePath: instancePath + "/x",
                    schemaPath: "#/properties/x/type",
                    keyword: "type",
                    params: { type: "number" },
                };
                if (vErrors === null) {
                    vErrors = [err3];
                } else {
                    vErrors.push(err3);
                }
                errors++;
            }
        }
        if (data.y !== undefined) {
            let data1 = data.y;
            if (!(typeof data1 == "number" && isFinite(data1))) {
                const err4 = {
                    instancePath: instancePath + "/y",
                    schemaPath: "#/properties/y/type",
                    keyword: "type",
                    params: { type: "number" },
                };
                if (vErrors === null) {
                    vErrors = [err4];
                } else {
                    vErrors.push(err4);
                }
                errors++;
            }
        }
        if (data.z !== undefined) {
            let data2 = data.z;
            if (!(typeof data2 == "number" && isFinite(data2))) {
                const err5 = {
                    instancePath: instancePath + "/z",
                    schemaPath: "#/properties/z/type",
                    keyword: "type",
                    params: { type: "number" },
                };
                if (vErrors === null) {
                    vErrors = [err5];
                } else {
                    vErrors.push(err5);
                }
                errors++;
            }
        }
    } else {
        const err6 = {
            instancePath,
            schemaPath: "#/type",
            keyword: "type",
            params: { type: "object" },
        };
        if (vErrors === null) {
            vErrors = [err6];
        } else {
            vErrors.push(err6);
        }
        errors++;
    }
    validate10.errors = vErrors;
    return errors === 0;
}
