/*
 * The MIT License
 *
 * Copyright 2025 Crow281.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
import { GENERATED_HEADER } from "./GeneratedHeader";
import { relative } from "node:path";
import { fileURLToPath } from "url";

/**
 * @param absoluteScriptFilePathURI
 * File path URI of the generation script.
 *
 * You would presumably pass the contents of import.meta.url.
 * @returns
 * A string, marking which script generated a given generated script.
 *
 * Note that this function expects you to be calling the scripts
 * from the project directory.
 */
export function createGeneratedHeaderComment(
    absoluteScriptFilePathURI: string,
): string {
    //File path containing script.
    const absoluteScriptFilePath: string = fileURLToPath(
        absoluteScriptFilePathURI,
    );

    //Calculate script file path relative to project.
    const scriptProjectFilePath: string = relative(
        process.cwd(),
        absoluteScriptFilePath,
    );

    return `${GENERATED_HEADER}
//This file was generated by script:
//${scriptProjectFilePath}`;
}
